# Generated by Django 5.1.1 on 2024-09-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('foto', models.ImageField(upload_to='images')),
                ('especialidade', models.CharField(choices=[('barba', 'Barba'), ('cabelo', 'Cabelo'), ('outro', 'Outros Serviços')], max_length=20)),
                ('contato', models.CharField(max_length=20)),
                ('historico', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('descricao', models.TextField(max_length=1000)),
                ('categoria', models.CharField(choices=[('barba', 'Barba'), ('cabelo', 'Cabelo'), ('outro', 'Outros Serviços')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo', models.IntegerField(max_length=3)),
            ],
        ),
    ]
