# Generated by Django 5.1.1 on 2024-09-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_barbearia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='descricao',
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao_curta',
            field=models.CharField(default='descricao', max_length=50),
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao_longa',
            field=models.TextField(default='descricao longa', max_length=500),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tempo',
            field=models.IntegerField(),
        ),
    ]
